timezone: Europe/Rome

mongo:
  database: aznLunch
  cluster: mongoforbot
  user: aznLunch
  jobs_collection: jobs
  job_file_name: job_tuples

job_time:
  save_interval: 5
  hours: 12
  minutes: 0
  seconds: 0

pdfcrowd:
  user: bacastelunch
  api_key: d5d3f3565a75ddcdb9b3a8b6f85a47d6

mail:
  address: mario.sequestro@libero.it
  imap_server: imapmail.libero.it
  imap_port: 993

lunchzone:
  CAPELLO:
    emoji: ğŸ’‡â€â™‚ï¸
    type: mail
    address: pasticceriacapellotorino@gmail.com

  VENTIDUE:
    emoji: 2ï¸âƒ£2ï¸âƒ£
    type: facebook
    address: Al-ventidue-1975069026112657

  MANGO's:
    emoji: ğŸ¥­ğŸ•
    type: facebook
    address: Viviana.Mango23

  OSTERIA:
    emoji: ğŸ‘©â€ğŸ³
    type: whatsapp
    address: ...

  AMICI_MIEI:
    emoji: ğŸ§‘ğŸ¾â€ğŸ¤â€ğŸ§‘ğŸ»
    type: web
    address: https://www.amicimieitorino.it/menu-pranzo/

